In [49]:
import pandas as pd
merged_df = pd.read_csv("merged_df.csv").drop_duplicates(subset=['fain_key'])
merged_df

,value,savings,description_doge,total_obligation,award_amount,link,fain_key,date,agency,funding_opportunity_goals,...,recipient_name,recipient_parent_name,primary_place_of_performance_scope,primary_place_of_performance_country_code,primary_place_of_performance_country_name,primary_place_of_performance_state_name,cfda_title,business_types_description,action_type_description,sector
0,34998729.0,12993908.00,USAID¿S RESEARCH FOR SCALABLE SOLUTIONS (R4S) ...,22004821.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA1...,7200AA19CA00041,3/1/2025,USAID,NaN,...,FAMILY HEALTH INTERNATIONAL,NaN,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development
2,34722274.0,9273274.00,TO PROVIDE SUPPORT FOR “FAMILY PLANNING AND RE...,25449000.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA20CA00016,3/1/2025,USAID,ORACLE.SQL.CLOB@736008DE,...,FAMILY HEALTH INTERNATIONAL,FAMILY HEALTH INTERNATIONAL,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development
4,140000000.0,73943882.00,THE MICROBICIDE 2021 INTRODUCTION AND ACCESS P...,66056118.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA21CA00011,3/1/2025,USAID,NOT APPLICABLE,...,FAMILY HEALTH INTERNATIONAL,FAMILY HEALTH INTERNATIONAL,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development
7,44996978.0,36180934.63,"WITH THIS ACTIVITY, USAID SEEKS TO ADVANCE NUT...",8816043.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA23CA00021,3/1/2025,USAID,NOT APPLICABLE,...,RESEARCH TRIANGLE INSTITUTE,RESEARCH TRIANGLE INSTITUTE,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development
9,260000.0,190957.00,PURPOSE: PURPOSE NORTH CAROLINA REMAINS AN UND...,260000.00,260000.0,https://usaspending.gov/award/ASST_NON_FHOI230...,FHOI230083,2/27/2025,Housing and Urban Development,NOT APPLICABLE,...,LEGAL AID OF NORTH CAROLINA INC,LEGAL AID OF NORTH CAROLINA INC,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,FAIR HOUSING ORGANIZATION INITIATIVES,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,Justice Social Equity and Community
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,299497.0,216446.00,UNCW ADVANCE CATALYST: : UNC-BY-THE-S.E.A. (ST...,299497.00,299497.0,https://usaspending.gov/award/ASST_NON_2427386...,2427386,4/25/2025,National Science Foundation,"THE GOAL OF THIS FUNDING OPPORTUNITY, ""ADVANCE...",...,UNIVERSITY OF NORTH CAROLINA AT WILMINGTON,NaN,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,STEM EDUCATION (FORMERLY EDUCATION AND HUMAN R...,PUBLIC/STATE CONTROLLED INSTITUTION OF HIGHER ...,NEW,Education
200,6983.0,6562.00,COLLABORATIVE RESEARCH: CONFERENCE: GA6 GEOSCI...,6983.00,6983.0,https://usaspending.gov/award/ASST_NON_2435273...,2435273,4/25/2025,National Science Foundation,NOT APPLICABLE,...,DUKE UNIVERSITY,DUKE UNIVERSITY,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,GEOSCIENCES,PRIVATE INSTITUTION OF HIGHER EDUCATION,NEW,Environment Climate Agriculture
201,281000.0,94350.00,LONGITUDINAL ANALYSIS OF EARLY INTERVENTIONAL ...,222153.03,20000.0,https://usaspending.gov/award/ASST_NON_N000142...,N000142412027,4/25/2025,Department of Defense,"DEVELOP LEARNERS KNOWLEDGE, SKILL, OR INTEREST...",...,EAST CAROLINA UNIVERSITY,NaN,STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,"SCIENCE, TECHNOLOGY, ENGINEERING & MATHEMATICS...",PUBLIC/STATE CONTROLLED INSTITUTION OF HIGHER ...,NEW,Education
220,59991.0,37496.00,DIGITAL HUMANITIES TEACHING AND LEARNING [THIS...,59991.00,59991.0,https://usaspending.gov/award/ASST_NON_ASB2997...,ASB29974024,4/4/2025,National Endowment for the Humanities,THE SPOTLIGHT ON HUMANITIES IN HIGHER EDUCATIO...,...,"NORTH CAROLINA WESLEYAN UNIVERSITY, INC.","NORTH CAROLINA WESLEYAN UNIVERSITY, INC.",STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,PROMOTION OF THE HUMANITIES TEACHING AND LEARN...,PRIVATE INSTITUTION OF HIGHER EDUCATION,NEW,Education
221,349991.0,123468.00,SNCC AND GRASSROOTS ORGANIZING: BUILDING A MOR...,349991.00,349991.0,https://usaspending.gov/award/ASST_NON_GG29318...,GG29318323,4/4/2025,National Endowment for the Humanities,NaN,...,DUKE UNIVERSITY,DUKE UNIVERSITY,STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,PROMOTION OF THE HUMANITIES PUBLIC PROGRAMS,OTHER,NEW,Justice Social Equity and Community

In [51]:
doge_grant = pd.read_csv("doge-scrape/data/doge-grant.csv")
doge_grant

C:\Users\aaanw\AppData\Local\Temp\ipykernel_10676\1929247963.py:1: DtypeWarning: Columns (78,79) have mixed types. Specify dtype option on import or set low_memory=False.
  doge_grant = pd.read_csv("doge-scrape/data/doge-grant.csv")

,date,agency,recipient,value,savings,link,description_doge,id,generated_unique_award_id,fain,...,place_of_performance_zip5,place_of_performance_address_line1,place_of_performance_address_line2,place_of_performance_address_line3,place_of_performance_foreign_province,place_of_performance_foreign_postal_code,funding_opportunity_number,funding_opportunity_goals,funding_agency,dt_scrape
0,3/26/2025,Department of Labor,International Labor Organization (ILO),2000000.0,1491000.0,https://usaspending.gov/award/ASST_NON_23K75IL...,PURPOSE: THE PROJECT AIMS TO PROMOTE THE RIGHT...,162221795.0,ASST_NON_23K75IL000001_1605,23K75IL000001,...,NaN,NaN,NaN,NaN,JORDAN,NaN,K-IL-23-002,NOT AVAILABLE,NaN,2025-04-04-0017
1,3/26/2025,Department of Labor,International Labor Organization (ILO),5000000.0,3935267.0,https://usaspending.gov/award/ASST_NON_23K75IL...,THE INTERNATIONAL LABOUR ORGANIZATION PROPOSES...,162779288.0,ASST_NON_23K75IL000002_1605,23K75IL000002,...,NaN,NaN,NaN,NaN,MEXICO,NaN,K-IL-23-003,NOT AVAILABLE,NaN,2025-04-04-0017
2,3/26/2025,Department of Labor,"Verite, Inc.",4455000.0,3630341.0,https://usaspending.gov/award/ASST_NON_24K75IL...,AWARD PURPOSE--THE PROTEGEMOS PROJECT WILL INC...,166579250.0,ASST_NON_24K75IL000006_1605,24K75IL000006,...,NaN,NaN,NaN,NaN,MEXICO,NaN,FOA-ILAB-23-27,OUTCOME 1: INCREASED CAPACITY OF MUNICIPAL STA...,NaN,2025-04-04-0017
3,3/26/2025,Department of Labor,Solidarity Center,6000000.0,4430876.0,https://usaspending.gov/award/ASST_NON_24K75IL...,PROMOTING QUALITY JOBS IN INFRASTRUCTURE DEVEL...,165942886.0,ASST_NON_24K75IL000007_1605,24K75IL000007,...,NaN,NaN,NaN,NaN,PHILIPPINES,NaN,FOA-ILAB-23-22,"OUTCOME 1: STRENGTHENED CAPACITY OF WORKERS, W...",NaN,2025-04-04-0017
4,3/26/2025,Department of Labor,International Labor Organization (ILO),6950000.0,6254552.0,https://usaspending.gov/award/ASST_NON_24K75IL...,THE PROPOSED PROJECT WILL GENERATE AND MOBILIZ...,166579251.0,ASST_NON_24K75IL000008_1605,24K75IL000008,...,NaN,NaN,NaN,NaN,UGANDA,NaN,K-IL-23-006,THE GOAL OF THIS GLOBAL PROJECT IS TO SUPPORT ...,NaN,2025-04-04-0017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24043,1/27/2025,Department of State,Redacted,6129.0,1532.0,NaN,Currently unavailable,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-06-29-1733
24044,1/24/2025,Department of State,Redacted,3000000.0,973916.0,NaN,Currently unavailable,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-06-29-1733
24045,5/13/2005,Environmental Protection Agency,Virginia Institute of Marine Science,1658232.0,894605.0,https://usaspending.gov/award/ASST_NON_8402480...,THE PURPOSE OF THE PROPOSED RESEARCH IS TO USE...,75624273.0,ASST_NON_84024801_6800,84024801,...,23062.0,NaN,NaN,NaN,NaN,NaN,EPA-G2021-ORD-F1,2 - TAKE DECISIVE ACTION TO ADVANCE ENVIRONMEN...,NaN,2025-06-29-1733
24046,7/16/2025,National Aeronautics and Space Administration,GEORGE WASHINGTON UNIVERSITY (THE),1174329.0,366992.0,https://usaspending.gov/award/ASST_NON_80NSSC2...,ASSESSING ENVIRONMENTAL JUSTICE AIR QUALITY ...,74737322.0,ASST_NON_80NSSC24K0503_080,80NSSC24K0503,...,20052.0,NaN,NaN,NaN,NaN,NaN,NOT APPLICABLE,22-IDS22-0007 ASSESSING ENVIRONMENTAL JUSTICE...,NaN,2025-07-26-2033
24047,6/6/2025,National Aeronautics and Space Administration,TRUSTEES OF TUFTS COLLEGE,911540.0,604288.0,https://usaspending.gov/award/ASST_NON_80NSSC2...,INTEGRATING EARTH OBSERVATIONS TOWARD ADVANCIN...,74738933.0,ASST_NON_80NSSC25K7031_080,80NSSC25K7031,...,2144.0,NaN,NaN,NaN,NaN,NaN,NNH23ZDA001N-EEJ,INTEGRATING EARTH OBSERVATIONS TOWARD ADVANCIN...,NaN,2025-07-26-2033

In [53]:
condensed = doge_grant[['fain', 'place_of_performance_county_name']].rename(columns={'fain': 'fain_key'})
condensed

            fain_key place_of_performance_county_name
0      23K75IL000001                              NaN
1      23K75IL000002                              NaN
2      24K75IL000006                              NaN
3      24K75IL000007                              NaN
4      24K75IL000008                              NaN
...              ...                              ...
24043            NaN                              NaN
24044            NaN                              NaN
24045       84024801                       GLOUCESTER
24046  80NSSC24K0503             DISTRICT OF COLUMBIA
24047  80NSSC25K7031                        MIDDLESEX

[24048 rows x 2 columns]

In [63]:
new_doge = pd.merge(merged_df, condensed, on = 'fain_key', how = 'left').drop_duplicates(subset=['fain_key'])

In [71]:
r1_counties = ['DURHAM', 'WAKE','MECKLENBURG', 'ORANGE', 'PITT']
new_doge['County with R1 University?'] = new_doge['place_of_performance_county_name'].isin(r1_counties)

In [73]:
new_doge

,value,savings,description_doge,total_obligation,award_amount,link,fain_key,date,agency,funding_opportunity_goals,...,primary_place_of_performance_scope,primary_place_of_performance_country_code,primary_place_of_performance_country_name,primary_place_of_performance_state_name,cfda_title,business_types_description,action_type_description,sector,place_of_performance_county_name,County with R1 University?
0,34998729.0,12993908.00,USAID¿S RESEARCH FOR SCALABLE SOLUTIONS (R4S) ...,22004821.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA1...,7200AA19CA00041,3/1/2025,USAID,NaN,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development,DURHAM,True
1,34722274.0,9273274.00,TO PROVIDE SUPPORT FOR “FAMILY PLANNING AND RE...,25449000.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA20CA00016,3/1/2025,USAID,ORACLE.SQL.CLOB@736008DE,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development,DURHAM,True
2,140000000.0,73943882.00,THE MICROBICIDE 2021 INTRODUCTION AND ACCESS P...,66056118.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA21CA00011,3/1/2025,USAID,NOT APPLICABLE,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development,DURHAM,True
3,44996978.0,36180934.63,"WITH THIS ACTIVITY, USAID SEEKS TO ADVANCE NUT...",8816043.00,0.0,https://usaspending.gov/award/ASST_NON_7200AA2...,7200AA23CA00021,3/1/2025,USAID,NOT APPLICABLE,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,USAID FOREIGN ASSISTANCE FOR PROGRAMS OVERSEAS,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,International Development,DURHAM,True
5,260000.0,190957.00,PURPOSE: PURPOSE NORTH CAROLINA REMAINS AN UND...,260000.00,260000.0,https://usaspending.gov/award/ASST_NON_FHOI230...,FHOI230083,2/27/2025,Housing and Urban Development,NOT APPLICABLE,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,FAIR HOUSING ORGANIZATION INITIATIVES,NONPROFIT WITH 501C3 IRS STATUS (OTHER THAN AN...,REVISION,Justice Social Equity and Community,WAKE,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,299497.0,216446.00,UNCW ADVANCE CATALYST: : UNC-BY-THE-S.E.A. (ST...,299497.00,299497.0,https://usaspending.gov/award/ASST_NON_2427386...,2427386,4/25/2025,National Science Foundation,"THE GOAL OF THIS FUNDING OPPORTUNITY, ""ADVANCE...",...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,STEM EDUCATION (FORMERLY EDUCATION AND HUMAN R...,PUBLIC/STATE CONTROLLED INSTITUTION OF HIGHER ...,NEW,Education,NEW HANOVER,False
104,6983.0,6562.00,COLLABORATIVE RESEARCH: CONFERENCE: GA6 GEOSCI...,6983.00,6983.0,https://usaspending.gov/award/ASST_NON_2435273...,2435273,4/25/2025,National Science Foundation,NOT APPLICABLE,...,SINGLE ZIP CODE,USA,UNITED STATES,NORTH CAROLINA,GEOSCIENCES,PRIVATE INSTITUTION OF HIGHER EDUCATION,NEW,Environment Climate Agriculture,DURHAM,True
105,281000.0,94350.00,LONGITUDINAL ANALYSIS OF EARLY INTERVENTIONAL ...,222153.03,20000.0,https://usaspending.gov/award/ASST_NON_N000142...,N000142412027,4/25/2025,Department of Defense,"DEVELOP LEARNERS KNOWLEDGE, SKILL, OR INTEREST...",...,STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,"SCIENCE, TECHNOLOGY, ENGINEERING & MATHEMATICS...",PUBLIC/STATE CONTROLLED INSTITUTION OF HIGHER ...,NEW,Education,NaN,False
106,59991.0,37496.00,DIGITAL HUMANITIES TEACHING AND LEARNING [THIS...,59991.00,59991.0,https://usaspending.gov/award/ASST_NON_ASB2997...,ASB29974024,4/4/2025,National Endowment for the Humanities,THE SPOTLIGHT ON HUMANITIES IN HIGHER EDUCATIO...,...,STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,PROMOTION OF THE HUMANITIES TEACHING AND LEARN...,PRIVATE INSTITUTION OF HIGHER EDUCATION,NEW,Education,NaN,False
107,349991.0,123468.00,SNCC AND GRASSROOTS ORGANIZING: BUILDING A MOR...,349991.00,349991.0,https://usaspending.gov/award/ASST_NON_GG29318...,GG29318323,4/4/2025,National Endowment for the Humanities,NaN,...,STATE-WIDE,USA,UNITED STATES,NORTH CAROLINA,PROMOTION OF THE HUMANITIES PUBLIC PROGRAMS,OTHER,NEW,Justice Social Equity and Community,NaN,False